"""SPIKE -- allocate DURING the call, at a size that only the kernel knows.

THE PREMISE BEING TESTED. We had assumed the thing impossible: Jax preallocates most of the GPU's
RAM, so there would be nothing left to take. This premise is wrong in principle -- XLA exposes its
own pool to the FFI handler: `XLA_FFI_DeviceMemory_Allocate` is a FIELD of the struct
`XLA_FFI_Api` ( `xla/ffi/api/c_api.h` ), hence of the stable C ABI, and not a header utility.

WHAT IT WOULD CHANGE. The shape of an OUTPUT must be known at trace time, and that will not change. An
INTERNAL size, no -- XLA never required it. An index built and consumed within the same call
could therefore be sized EXACTLY, with no guessed bound, and under `jit`. That is the difference
with `scratch_attributes`, whose capacity comes down from Python.

WHAT THIS TEST ESTABLISHES, AND WHAT IT DOES NOT. On CPU, it establishes it for real: three
different internal sizes for a single source, exact, with no bound -- and the same thing UNDER
`jit`. There, the memory comes from an `aligned_alloc` of the handler, not from XLA: the CPU backend answers
"No device memory allocator available on this platform", and it is right, there is no device
( this is what the first version of this spike showed, which went through XLA's pool everywhere ).

On GPU the XLA pool will indeed be needed, and THAT IS NOT TESTED HERE: nvcc 13.4 segfaults on the
CUDA source generated by loom, at -O0 and after a successful preprocessing, independently of this spike
( reproduced without it ). The test therefore also accepts a refusal, as long as it is READABLE -- because
a clean refusal is correct behavior, whereas a segfault, a silence or a wrong result
are not.
"""
import loom
from loom import Axis, ShapeVar, RealTensor, driver
from loom.compilation.FfiCode import FfiCode
from errand import test

import numpy


# The body IS the handler ( `FfiCode.handler` ): it is host code, it needs `scratch`, and
# there is no item to scaffold around it. `allocator = True` is what makes XLA's allocator get
# bound -- an opt-in, because the name of a kernel is the hash of its source and a `Bind()`
# clause added unconditionally would recompile the whole repository.
#
# NB the compaction loop is bounded by `compact.shape( 0 )` AND NOT by the input. This is THE
# move that makes a refusal harmless: `Scratch::view` returns an EMPTY view when the pool says no, and
# a body that loops over its own size then does nothing. The first version of this test
# bounded on the input and wrote through a null pointer -- that segfault is what revealed the
# CPU refusal.
_CODE = """
    void kernel( auto &&queue, auto &&batch_axes, auto &&args ) {
        // what only the kernel knows: how many entries are positive. No bound was
        // given, neither by Python nor by XLA.
        SI n = 0;
        for ( SI i = 0; i < args.inputs.values.shape( 0 ); ++i )
            if ( args.inputs.values( i ) > 0 )
                ++n;

        // ... and we allocate EXACTLY that. `allocator` is in `args`: allocating is a host
        // operation, so it has no business in the kernel form.
        auto compact = args.allocator.template view<double>( n );

        // the loop is bounded by THE VIEW and not by the input: this is what makes a refusal
        // harmless ( see Scratch.h ).
        SI k = 0;
        for ( SI i = 0; i < args.inputs.values.shape( 0 ) && k < compact.shape( 0 ); ++i )
            if ( args.inputs.values( i ) > 0 )
                compact( k++ ) = args.inputs.values( i );

        double s = 0;
        for ( SI i = 0; i < compact.shape( 0 ); ++i )
            s += compact( i );

        args.outputs.total( 0 ) = s;
        args.outputs.total( 1 ) = double( compact.shape( 0 ) );
    }
"""


def _call( values ):
    """`( sum of the positives, how many )`, passed through an internal buffer of exact size --
    or `None` if the platform refuses to allocate."""
    v = RealTensor[ Axis( ShapeVar( len( values ) ), name = "num_point" ) ]( values )
    total = RealTensor[ Axis( ShapeVar( 2 ), name = "num_output" ) ]()
    try:
        loom.ffi_call(
            "test_scratch_positives",
            FfiCode( code = _CODE, allocator = True ),
            values = v,
            total = loom.out( total ),
        )
    except Exception as e:
        # a refusal, and it must be READABLE: that is half of the contract.
        assert "RESOURCE_EXHAUSTED" in str( e ), e
        assert "scratch" in str( e ), e
        return None
    raw = total.raw.tolist()
    return raw[ 0 ], int( raw[ 1 ] )


if test( "allocates_the_exact_size" ):
    # three DIFFERENT useful sizes for a single source: if the capacity had to be prescribed,
    # a bound would be needed here -- hence waste, or truncation.
    cas = ( ( [ 1.0, -2.0, 3.0 ], 4.0, 2 ),
            ( [ -1.0, -2.0, -3.0 ], 0.0, 0 ),
            ( [ 5.0 ] * 17, 85.0, 17 ) )

    served = None
    for data, expected, how_many in cas:
        res = _call( data )
        if res is None:
            # the platform does not allocate. The only case that must still pass is the one that
            # asks for nothing: zero elements are not allocated, so nothing can be refused.
            assert how_many > 0, ( "an allocation of 0 elements was refused -- `Scratch::view` "
                                  "must short-circuit before calling the pool", data )
            served = False
            continue
        assert abs( res[ 0 ] - expected ) < 1e-12, ( data, res )
        assert res[ 1 ] == how_many, ( data, res )
        if how_many > 0:
            served = True

    print( "scratch: served by the platform" if served else
           "scratch: plumbing ok, but the platform REFUSES to allocate ( CPU: \"No device "
           "memory allocator available on this platform\" )" )


if test( "under_jit" ):
    # THE point of the spike. An OUTPUT whose shape depends on the data is impossible under `jit` and will
    # stay so. An INTERNAL size would work: the shape of the buffer is not in the XLA program,
    # it only exists when the handler runs. This test checks it where it is served, and otherwise
    # checks that the refusal goes through `jit` cleanly rather than corrupting a result.
    n = 64

    def loss( x ):
        v = RealTensor[ Axis( ShapeVar( n ), name = "num_point" ) ]( x )
        total = RealTensor[ Axis( ShapeVar( 2 ), name = "num_output" ) ]()
        loom.ffi_call(
            "test_scratch_positives",
            FfiCode( code = _CODE, allocator = True ),
            values = v,
            total = loom.out( total ),
        )
        return total.value[ 0 ]

    compile = driver.jit( loss )
    rng = numpy.random.default_rng( 0 )

    refuse = False
    for _ in range( 3 ):
        x = rng.normal( size = n )
        expected = float( x[ x > 0 ].sum() )
        try:
            got = float( compile( driver.array( x ) ) )
        except Exception as e:
            assert "RESOURCE_EXHAUSTED" in str( e ), e
            refuse = True
            break
        assert abs( got - expected ) < 1e-10, ( got, expected )

    print( "scratch under jit: clean refusal, no wrong result" if refuse else
           f"scratch under jit: { n } entries, variable internal size -- ok" )
