#pragma once

#include "../common_macros.h"
#include "Tuple.h" // Tuple, tuple, map
#include <type_traits>

namespace sdot {

/// Common base of the named axis types generated by DEFINE_AXIS (used to detect them).
struct AxisBase {};

/// Unnamed axis (placeholder): default value of the AxisNames entries.
struct UnnamedAxis : AxisBase {
    HD void display( auto &os ) const { os << "_"; }
};

/// Index attached to a named axis (result of `axis = index`), consumed by
/// `TensorView::operator()` / `squeeze` to remove the `axis_type` axis at position `index`.
///
/// `Optional` says what an argument WITHOUT that axis must do. A user index (`dim = 0`) is
/// strict: a name the tensor does not have is a typo, and the compiler says so. A BATCH index is
/// not: a `vmap` axis is carried by the arguments it maps and by them only, so `x( batch_index )`
/// has to leave the others untouched -- which is what makes ONE body work batched or not.
template<class AxisType, class Index, bool Optional = false>
struct AxisIndex {
    using                  axis_type = AxisType;
    static constexpr bool  optional  = Optional;
    Index                  index;
};

/// An index an argument may ignore: what a batch multi-index is made of (see `CartesianIndices`).
HD constexpr auto optional_axis_index( auto axis, auto index ) {
    return AxisIndex<DECAYED_TYPE_OF( axis ),DECAYED_TYPE_OF( index ),true>{ index };
}

// --- traits -------------------------------------------------------------------------------
template<class A>                 constexpr bool is_axis               = std::is_base_of_v<AxisBase, A>;
template<class>                   struct IsAxisIndex                     : std::false_type {};
template<class A,class I,bool O>  struct IsAxisIndex<AxisIndex<A,I,O>>   : std::true_type  {};

/// Position (compile-time) of a named axis `Name` in a `Tuple` of names; -1 if absent.
template<class Name,class Tup> struct AxisPos;
template<class Name>                        struct AxisPos<Name,Tuple<>>            { static constexpr int value = -1; };
template<class Name,class Head,class... Tl> struct AxisPos<Name,Tuple<Head,Tl...>> {
    static constexpr int rest  = AxisPos<Name,Tuple<Tl...>>::value;
    static constexpr int value = std::is_same_v<Head,Name> ? 0 : ( rest < 0 ? -1 : rest + 1 );
};

/// THE COORDINATE of a multi-index along a named axis: `coord( item, y )`.
///
/// A multi-index is a `Tuple` of `AxisIndex` ( see `CartesianIndices` ). A TENSOR consumes it
/// by name on its own -- `next( item )` -- but a hand-written header wants INTEGERS: its
/// functions take `( j, i )`. That is what this returns.
///
/// ( `item[ y ]` would be shorter, but `Tuple` cannot know the axes: it is `AxisNames.h`
///   that includes `Tuple.h`, not the other way round. It would take a wrapper type for named
///   multi-indices, transparent everywhere `x( batch_index )` is already written. )
template<class Axis>
HD constexpr auto coord( const auto &item, Axis axis ) {
    using I = DECAYED_TYPE_OF( item );
    if constexpr ( I::ct_size == 0 )
        // no `static_assert( false )`: it would be evaluated even in a discarded branch. Calling
        // a member that does not exist names the faulty axis in the compiler message.
        return axis.this_multi_index_has_no_such_axis();
    else {
        auto head = item[ Ct<int,0>() ];
        using H = DECAYED_TYPE_OF( head );
        if constexpr ( IsAxisIndex<H>::value && std::is_same_v<typename H::axis_type,Axis> )
            return head.index;
        else
            return coord( item.without_index( Ct<int,0>() ), axis );
    }
}

/// `Tuple` of "all unnamed" axes sized like `shape` (only its type is taken:
/// default value of `AxisNames`).
HD constexpr auto unnamed_axes( auto shape ) {
    return map( shape, []( auto ) { return UnnamedAxis{}; } );
}

/// Defines a named axis type + an object usable as `t( NAME = i )` / `squeeze( NAME, i )`.
#define DEFINE_AXIS( NAME )                                                                 \
    struct _##NAME : ::sdot::AxisBase {                                                     \
        HD constexpr auto operator=( auto index ) const {                                  \
            return ::sdot::AxisIndex<_##NAME,DECAYED_TYPE_OF( index )>{ FORWARD( index ) }; \
        }                                                                                  \
        void display( auto &os ) const { os << #NAME; }                                    \
    };                                                                                     \
    LOOM_TAG( _##NAME, NAME )

} // namespace sdot
