#pragma once

#include "CpuKernelMemorySpace.h"
#include "CpuHostMemorySpace.h"
#include "../common_macros.h"
#include "../common_types.h"
#include "CpuThreadPool.h"
#include "Machine.h"
#include "QueueEvent.h"
#include "IoCategory.h"
#include "Reducer.h"
#include "Group.h"
#include "../Ct.h"

#include <functional>
#include <barrier>
#include <thread>
#include <vector>
#include <memory>
#include <tuple>

namespace sdot {

/// The CPU execution context: the process's thread queue (`cpu_thread_pool()`, in the
/// runtime library), and the two launch forms a kernel can ask for
/// (`submit_kernel`, `submit_kernel_grouped`).
///
/// This is WHERE everything CPU-specific lives -- the loop over items, the split between
/// threads, the per-thread reductions. `run_parallel` knows nothing about the device: it peels the
/// input/output categories, makes the arguments available, and calls `submit_kernel( queue, ... )` --
/// one overload per queue type, found by ADL. Adding a device = writing its queue and its
/// two `submit_kernel`, not an `if` in `run_parallel`.
///
/// Each "virtual thread" `t` of `[ 0, nb_threads )` handles a CONTIGUOUS slice of the items
/// (`[ t n / T, ( t + 1 ) n / T )`), see `CpuThreadPool`. The body's contract does not change:
/// `thread_index` is unique and STABLE for everything a thread handles (one scratch row per
/// thread), and `nb_threads` is their count.
///
// ── the free form, declared elsewhere ──────────────────────────────────────────────────────
/// declared by `run_parallel.h` ( which includes us ): the FREE form, which the method below
/// calls. Redeclared here so that the method can name it without depending on the order of
/// includes.
auto run_parallel( auto &&queue_list, auto &&second, auto &&...rest );

/// A trivially copyable handle.
struct CpuQueue {
    /// default memory area seen by kernels launched on this queue (an execution
    /// context may expose several areas; this one is the default)
    using DefaultKernelMemorySpace = CpuKernelMemorySpace;

    CpuQueue() : pool( &cpu_thread_pool() ) {}

    void run_threads( int nb_threads, const std::function<void( int )> &job ) const { pool->run_threads( nb_threads, job ); }
    int  nb_workers () const { return pool->nb_workers(); }

    /// what a kernel can know about this machine ( see `Machine.h` ). No lanes, hence no
    /// sub-group: everything is 1, and the shared-memory budget is notional -- `CpuQueue` takes
    /// a `std::vector` on the heap, there is no hardware limit to announce.
    Machine machine() const {
        return { SI( pool->nb_workers() ), 1, cpu_notional_local_mem_bytes, 1 };
    }


    /// LAUNCH: `queue.run_parallel( Functor(), domain, args )`.
    ///
    /// Three things, and not a list of ( io, value ) pairs: `args` goes through in ONE piece, its
    /// generated `kernel_form` carrying each argument's io policy. The functor thus receives
    /// `( item, args )`, where `args` is the KERNEL form -- same data, without the queue.
    ///
    /// The free form `sdot::run_parallel( queue, domain, func, io, value, ... )` remains for
    /// whoever wants another policy or a subset.
    auto run_parallel( auto &&func, auto &&items, auto &&args ) {
        return sdot::run_parallel( *this, FORWARD( items ), FORWARD( func ), MutList(), FORWARD( args ) );
    }

    /// the same, passing ONE more value to the functor -- typically `batch_axes`, whose body
    /// needs it to isolate its own axes ( `coords.axes - batch_axes` ).
    auto run_parallel( auto &&func, auto &&items, auto &&args, auto &&extra ) {
        return sdot::run_parallel( *this, FORWARD( items ), FORWARD( func ),
                                   MutList(), FORWARD( args ), InpList(), FORWARD( extra ) );
    }

    CpuThreadPool *pool;
};

/// Transfer cost (seconds per byte) to make a source area accessible from this
/// execution context. A context knows the areas it can reach (not the reverse),
/// so these overloads live next to the context.
///   CPU -> CPU: the data is already in host RAM, nothing to transfer.
constexpr auto transfer_cost_per_byte( const CpuQueue &, CpuHostMemorySpace ) { return Ct<double,0.0>(); }

namespace detail::CpuQueueLaunch {
    /// call of the body for an item, with or without the thread info depending on what `func` accepts
    /// (bodies generated by `FfiCode.per_item` take them; `TensorView::fill_with` does not).
    ///
    /// `flat_index` IS THE FLAT RANK OF THE ITEM in the traversed domain -- "who am I?". It
    /// was already there, in the loop variable; it simply did not get passed through. Failing
    /// that, every kernel that needed it built a pretext aggregate carrying an
    /// `iota` ( `examples/splats::Rangs`, and the same in `examples/diffusion` before it ) --
    /// an entire extra tensor, written and read, for a number the loop already knew.
    void call( auto &&func, auto &&item, SI flat_index, int thread_index, int nb_threads, auto &...reducers_and_args ) {
        if constexpr ( requires { func( item, flat_index, thread_index, nb_threads, reducers_and_args... ); } )
            func( item, flat_index, thread_index, nb_threads, reducers_and_args... );
        else if constexpr ( requires { func( item, thread_index, nb_threads, reducers_and_args... ); } )
            func( item, thread_index, nb_threads, reducers_and_args... );
        else
            func( item, reducers_and_args... );
    }

    /// the cooperative counterpart of `call`: the flat rank is added the same way, and a functor
    /// that does not take it keeps working.
    HD_INLINE void call_grouped( auto &&func, auto &&item, SI flat_index, auto &&...rest ) {
        if constexpr ( requires { func( item, flat_index, rest... ); } )
            func( item, flat_index, rest... );
        else
            func( item, rest... );
    }

    /// one reduction row per virtual thread, initialized to the identity
    template<class Op,class T>
    auto partials_for( const ReductionTarget<Op,T> &target, int nb_threads ) {
        return std::vector<Reducer<Op,T>>( nb_threads, Reducer<Op,T>{ target.op, Reducer<Op,T>::identity( target.op ) } );
    }
}

/// Flat launch: `nb_threads` virtual threads, each with its slice of items. `reduction_targets`
/// is a `std::tuple` of `ReductionTarget` (op + host pointer), peeled by `run_parallel` off the
/// head of the arguments; each thread accumulates in its own `Reducer`, combined at the end.
/// Synchronous (the queue returns once everything is done): the returned event is already complete.
/// The `deps` dependencies are awaited before starting (free if they already are done).
auto submit_kernel( const CpuQueue &queue, const auto &deps, auto &&func, auto &&item_list,
                    int nb_items, int nb_threads, auto reduction_targets, auto &&...args ) {
    deps.wait_all();
    return std::apply( [&]( auto &...targets ) {
        auto partials = std::make_tuple( detail::CpuQueueLaunch::partials_for( targets, nb_threads )... );
        std::apply( [&]( auto &...vecs ) {
            queue.run_threads( nb_threads, [&]( int t ) {
                const int b = int( ( long long ) t * nb_items / nb_threads );
                const int e = int( ( long long ) ( t + 1 ) * nb_items / nb_threads );
                for ( int index = b; index < e; ++index )
                    detail::CpuQueueLaunch::call( func, item_list[ index ], SI( index ), t, nb_threads, vecs[ t ]..., args... );
            } );
            // combining the rows into the host target
            ( [&]( auto &target, auto &vec ) {
                for ( auto &r : vec )
                    *target.host = target.op( *target.host, r.value );
            }( targets, vecs ), ... );
        }, partials );
        return QueueEvent{};
    }, reduction_targets );
}

/// Cooperative launch: a GROUP of `group_size` lanes per concurrent item (`nb_groups` groups
/// in flight), which share `local_scratch` (`local_elems` `int32` words) and synchronize through
/// `group_barrier( group )`.
///
/// `group_size == 1` (production on CPU, see `Cpu.group_size` on the python side) reduces to the
/// flat launch: one lane, no barrier, one scratch per thread. Beyond that, each group is
/// `group_size` system threads around a `std::barrier` -- correct, not fast: it is the path
/// that runs on CPU a kernel written for GPU groups, for testing purposes.
auto submit_kernel_grouped( const CpuQueue &queue, const auto &deps, auto &&func, auto &&item_list,
                            int nb_items, int nb_groups, int group_size, int local_elems, auto reduction_targets, auto &&...args ) {
    deps.wait_all();
    static_assert( std::tuple_size_v<DECAYED_TYPE_OF( reduction_targets )> == 0,
                   "reductions are not supported in a group kernel" );
    const int scratch_stride = std::max( local_elems, 1 );
    std::vector<std::int32_t> scratch( std::size_t( scratch_stride ) * std::size_t( nb_groups ) );

    if ( group_size <= 1 ) {
        queue.run_threads( nb_groups, [&]( int g ) {
            CpuGroup    group{ nullptr, 1 };
            CpuSubGroup sub_group{ 0, 1 };
            std::int32_t *local_scratch = scratch.data() + std::size_t( g ) * scratch_stride;
            for ( int index = g; index < nb_items; index += nb_groups )
                detail::CpuQueueLaunch::call_grouped( func, item_list[ index ], SI( index ), g, 0, 1, group, local_scratch, sub_group, args... );
        } );
        return QueueEvent{};
    }

    // a group = `group_size` system threads and a barrier; the groups run in parallel
    std::vector<std::thread> lanes;
    lanes.reserve( std::size_t( nb_groups ) * group_size );
    std::vector<std::unique_ptr<std::barrier<>>> barriers;
    barriers.reserve( nb_groups );
    for ( int g = 0; g < nb_groups; ++g ) {
        barriers.emplace_back( std::make_unique<std::barrier<>>( group_size ) );
        for ( int lane = 0; lane < group_size; ++lane ) {
            lanes.emplace_back( [&,g,lane] {
                CpuGroup    group{ barriers[ g ].get(), group_size };
                CpuSubGroup sub_group{ lane, 1 };
                std::int32_t *local_scratch = scratch.data() + std::size_t( g ) * scratch_stride;
                for ( int index = g; index < nb_items; index += nb_groups )
                    detail::CpuQueueLaunch::call_grouped( func, item_list[ index ], SI( index ), g, lane, group_size, group, local_scratch, sub_group, args... );
            } );
        }
    }
    for ( auto &th : lanes )
        th.join();
    return QueueEvent{};
}

} // namespace sdot
